global:
  resolve_timeout: 5m
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'alertmanager@infralab.local'
  smtp_require_tls: false

route:
  receiver: 'mailhog'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'mailhog'
    email_configs:
      - to: 'admin@infralab.local'
        send_resolved: true
