groups:
  - name: container_alerts
    rules:
      - alert: ContainerDown
        expr: up == 0
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "🔴 {{ $labels.job }} - {{ $labels.instance }} est DOWN"
          description: "Le service {{ $labels.job }} sur {{ $labels.instance }} ne répond plus depuis 15s."

      - alert: WebappDown
        expr: up{job="webapp"} == 0
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "🔴 WEBAPP DOWN: {{ $labels.instance }}"
          description: "Le conteneur webapp {{ $labels.instance }} est arrêté depuis 15 secondes."

      - alert: HighCpuUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "⚠️ CPU élevé sur {{ $labels.instance }}"
          description: "Usage CPU > 80% depuis 2 minutes."

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "⚠️ RAM élevée sur {{ $labels.instance }}"
          description: "Usage mémoire > 85% depuis 2 minutes."

      - alert: ContainerHighCpu
        expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "⚠️ Container {{ $labels.name }} CPU élevé"
          description: "Le conteneur {{ $labels.name }} utilise beaucoup de CPU."

      - alert: ContainerHighMemory
        expr: container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes{name!=""} * 100 > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "⚠️ Container {{ $labels.name }} RAM élevée"
          description: "Le conteneur {{ $labels.name }} utilise > 85% de sa limite mémoire."

      - alert: DiskSpaceLow
        expr: (1 - node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "⚠️ Disque presque plein"
          description: "Usage disque > 80% sur {{ $labels.instance }}."
